name: Build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * 0'

jobs:
  build-and-push-image:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Pull Code
        uses: actions/checkout@v4

      - name: Build and Push
        uses: KuhlTime/ghcr-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
