name: Build

on:
  workflow_dispatch:

jobs:
  build-and-push-image:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Pull Code
        uses: actions/checkout@v4

      - name: Build
        run: docker build -t ghcr.io/karlgong/qops-one-test-github-runner:latest .

      - name: Push
        run: docker push ghcr.io/karlgong/qops-one-test-github-runner:latest
